apiVersion: 1

datasources:
  - name: EF Postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: user
    database: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: password
